### ISSUE TITLE
provide notifications when a backup failed

### ISSUE THREAD

**Issue by Akruidenberg** [Fekide/volumerize#16]
it would be nice to receive notifications when a backup failed or completed. 

Maybe you can apprise for this? There are docker containers for this.

Thanks in advance!

**Comment by sargreal** [comment]
Yes, this sounds like a good idea!

This is exactly why it is possible to customize the jobber file to add new result sinks (for example a script to send an email or send to a slack webhook).

I can think about adding a better way to configure this, without needing to overwrite the whole  jobber config. However I don’t think we can support all the different ways to send notifications.

What images are you talking about specifically?

**Comment by Akruidenberg** [comment]
> Yes, this sounds like a good idea!
> 
> This is exactly why it is possible to customize the jobber file to add new result sinks (for example a script to send an email or send to a slack webhook).
> 
> I can think about adding a better way to configure this, without needing to overwrite the whole jobber config. However I don’t think we can support all the different ways to send notifications.
> 
> What images are you talking about specifically?

there are some examples. see:


https://hub.docker.com/r/linuxserver/apprise-api
https://hub.docker.com/r/mazzolino/apprise-microservice (bit dated, maybe forking?)

Hope this helps. i've not using this myself. in the past i have seen some backup tools using Apprise.
