### ISSUE TITLE
How to use ftps?

### ISSUE THREAD

**Issue by Akruidenberg** [Fekide/volumerize#17]
I've been testing this docker image with some test volumes and this is working fine so far with a local backup folder.
However, i would like to setup another job with FTPS, but I don't get it working. 
Volumerize won't connect with my FritzBox. When searching for the docs for Duplicity, it looks like I need to fill in a env. See:

http://duplicity.nongnu.org/docs.html

However, i don't know where to put this password in duplicity. Duplicati is working fine with my Fritzbox, that's not the problem. 
I; ve tried the following for the `VOLUMERIZE_TARGET` parameter:

ftps://user:secretpassword@example.example.com:port/duplicity

What is the right configuration to use volumerize with ftps?

**Comment by sargreal** [comment]
You should only have to add the environment variable as `FTP_PASSWORD`.

Volumerize forwards all non-defined variables to duplicity.

If you want or need it, i can also add it to the variables that can be used as docker secrets

**Comment by Akruidenberg** [comment]
> FTP_PASSWORD

Thank you for your answer. From a security standpoint, it would be nice to have. :)
