### ISSUE TITLE
make it possible to run the container without root 

### ISSUE THREAD

**Issue by Akruidenberg** [Fekide/volumerize#19]
When running the container with tthe --user flag, i''ve got the following errors in the logs:

`touch: /root/.jobber: Permission denied`

From security perspective its not an good idea to run containers with root.  It would be nice to running this rootless.

Thanks in advance!

**Comment by sargreal** [comment]
Yes you are right, the reason for why it is root as default, is that it may need to backup volumes from different containers with different users at the same time. Even if the backup may work, the restoring will not.

But you are right, there should at least be the option to run it as non-root.
