### ISSUE TITLE
How to backup Postgres and Mariadb ath the same time with prepost?

### ISSUE THREAD

**Issue by Akruidenberg** [Fekide/volumerize#22]
I have multiple containers running with postgres and Mariadb databases, and wants to make a single job to  dump both my mariadb and postgress databases in a single database.

Now, we have separate tags for both mariadb and postgres. I don't know exactly how to integrate this with my Volumerize. 
Is Volumerize's idea to have seprate containers for this?

Maybe we can make single container with the added databases and env's?

Thanks in advance!

**Comment by Akruidenberg** [comment]
Do I still need a separate container for this?

**Comment by sargreal** [comment]
> Do I still need a separate container for this?

No, you only need to specify the environment variables for both backup strategies to your liking. The backups from different database-strategies are all saved and imported in different directories inside the selected `VOLUMERIZE_SOURCE`, so they don't interfere with each other

**Comment by Akruidenberg** [comment]
> > Do I still need a separate container for this?
> 
> No, you only need to specify the environment variables for both backup strategies to your liking. The backups from different database-strategies are all saved and imported in different directories inside the selected `VOLUMERIZE_SOURCE`, so they don't interfere with each other

Thanks!
