### ISSUE TITLE
Problem connecting to Minio

### ISSUE THREAD

**Issue by miguelmartinez1024** [Fekide/volumerize#25]
HI All, I'm having trouble connecting to a self-hosted Minio server and I've been digging through the documentation and examples with no luck. 

### Actual behavior:
Volumerize does not connect or backup to Minio server. 
Instead, I get this console log:
```
volumerize_1      | root: /etc/volumerize/periodicBackup
volumerize_1      | ExecAndWait: /bin/sh: exit status 23
volumerize_1      | {"fate":1,"job":{"command":"/etc/volumerize/periodicBackup","name":"VolumerizeBackupJob","status":"Good","time":"46 * * * * *"},"startTime":1627573546,"stderr":"running /postexecute/backup/0-removeoldbackup.sh\nChecking if old backups should be removed\n\nrunning /postexecute/backup/1-replicate.sh\n\n","stdout":"running /postexecute/backup/0-removeoldbackup.sh\nChecking if old backups should be removed\n\nrunning /postexecute/backup/1-replicate.sh\n\n","succeeded":false,"user":"root","version":"1.4"}
```

### Expected behavior:
Volumerize connects to minio and is able to backup volumes.

Here is part of my docker-compose:
```
  volumerize :
    image: fekide/volumerize
    volumes: 
      - db:/source:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - volumerize_cache:/volumerize-cache
    environment: 
      - VOLUMERIZE_SOURCE=/source:ro
      - "VOLUMERIZE_TARGET=s3:https://minio.domain.com:443/bucket-name"
      - VOLUMERIZE_CONTAINERS=db_node
      - "AWS_ACCESS_KEY_ID=AAAAAAAAAAAAAAA"
      - "AWS_SECRET_ACCESS_KEY=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
      - VOLUMERIZE_JOBBER_TIME=46 * * * *
      - DEBUG=true
      - TZ=America/Los_Angeles
    depends_on: 
      - db_node
    restart: always
```

For reference, using the Minio python package I'm able to connect like this:
```
client = Minio('minio.domain.com',
               access_key='AAAAAAAAAAAAAAA',
               secret_key='BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
               secure=True)
```

Other info - 
- Minio server is running behind nginx proxy and only ports 80 & 443 are open.

I would appreciate some feedback or suggestions. I've tried changing VOLUMERIZE_TARGET from "s3" to "minio" and removing "https" & ":443".

Thanks

**Comment by sargreal** [comment]
Thanks for your issue @miguelmartinez1024 !

As far as I can tell, this has to do with duplicity. I think this comment should solve it: [duplicity#59#note_595889998](https://gitlab.com/duplicity/duplicity/-/issues/59#note_595889998)

It seems that you need to use `boto+s3:///bucket-name` as target and add the variable `VOLUMERIZE_DUPLICITY_OPTIONS=--s3-endpoint-url=https://minio.domain.com:443`

Could you please try if that solves the issue?

**Comment by sargreal** [comment]
Assumed as fixed
