### ISSUE TITLE
Does this image support a remote docker host?

### ISSUE THREAD

**Issue by JohnShortland** [Fekide/volumerize#27]
Does this image support a remote docker host?

A lot of containers allow setting a variable such as:

DOCKER_HOST

**Comment by sargreal** [comment]
This image uses a standard docker cli for starting and stopping containers.

As such all of the [environment variables described in the documentation](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables) can be used

**Comment by JohnShortland** [comment]
@sargreal Excellent, thank you
