### ISSUE TITLE
Support docker swarm

### ISSUE THREAD

**Issue by sargreal** [Fekide/volumerize#9]
Docker swarm is an alternative/ more scalable container orchestration than docker-compose. It should also be supported with corresponding utilities. 

It is currently only possible to stop containers. Possible additions for docker swarm or also in general are:
- execute job in container (for example set maintenance mode or execute backup utility in the container)
- scale service 

Passcodes are currently stored in environment variables. It should also be possible to use `_FILE` environment variables

**Comment by sargreal** [comment]
Support for docker swarm now includes:
- utility to get task of service
- enable `file_env` variables for passwords and targets

Scaling and directly executing is not included because of unusefulness with cli options

**Comment by dreaded369** [comment]
Is there documentation for this?
Does "utility to get task of service" overcome the issue of not being able to stop and start containers using VOLUMERIZE_CONTAINERS because swarm adds a hash to the container name which is unpredictable?
